// <auto-generated />
using System;
using FaleMaisPersistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FaleMaisPersistence.Migrations
{
    [DbContext(typeof(FaleMaisDbContext))]
    [Migration("20200901212738_FixPriceColumnTypo")]
    partial class FixPriceColumnTypo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FaleMaisDomain.Entities.City", b =>
                {
                    b.Property<byte>("AreaCode")
                        .HasColumnName("area_code")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 27, 38, 660, DateTimeKind.Local).AddTicks(2407));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 27, 38, 664, DateTimeKind.Local).AddTicks(8302));

                    b.HasKey("AreaCode");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("FaleMaisDomain.Entities.Price", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 27, 38, 667, DateTimeKind.Local).AddTicks(9541));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("FromAreaCode")
                        .HasColumnName("from_area_code")
                        .HasColumnType("smallint");

                    b.Property<byte?>("FromCityAreaCode")
                        .HasColumnType("smallint");

                    b.Property<float>("PricePerMinute")
                        .HasColumnName("price_per_minute")
                        .HasColumnType("real");

                    b.Property<byte>("ToAreaCode")
                        .HasColumnName("to_area_code")
                        .HasColumnType("smallint");

                    b.Property<byte?>("ToCityAreaCode")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 27, 38, 667, DateTimeKind.Local).AddTicks(9847));

                    b.HasKey("Id");

                    b.HasIndex("FromCityAreaCode");

                    b.HasIndex("ToCityAreaCode");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("FaleMaisDomain.Entities.Price", b =>
                {
                    b.HasOne("FaleMaisDomain.Entities.City", "FromCity")
                        .WithMany("PricesToFrom")
                        .HasForeignKey("FromCityAreaCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FaleMaisDomain.Entities.City", "ToCity")
                        .WithMany("PricesFromTo")
                        .HasForeignKey("ToCityAreaCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
