// <auto-generated />
using System;
using FaleMaisPersistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FaleMaisPersistence.Migrations
{
    [DbContext(typeof(FaleMaisDbContext))]
    [Migration("20200902181811_FixesToDatabase")]
    partial class FixesToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FaleMaisDomain.Entities.AreaCode", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("area_code")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 2, 15, 18, 11, 554, DateTimeKind.Local).AddTicks(4776));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 2, 15, 18, 11, 561, DateTimeKind.Local).AddTicks(5855));

                    b.HasKey("Id");

                    b.ToTable("AreaCodes");

                    b.HasData(
                        new
                        {
                            Id = (byte)68,
                            Name = "Acre"
                        },
                        new
                        {
                            Id = (byte)82,
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = (byte)96,
                            Name = "Amapá"
                        });
                });

            modelBuilder.Entity("FaleMaisDomain.Entities.Call", b =>
                {
                    b.Property<byte>("FromAreaCode")
                        .HasColumnName("from_area_code")
                        .HasColumnType("smallint");

                    b.Property<byte>("ToAreaCode")
                        .HasColumnName("to_area_code")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 2, 15, 18, 11, 567, DateTimeKind.Local).AddTicks(2170));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("PricePerMinute")
                        .HasColumnName("price_per_minute")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 2, 15, 18, 11, 567, DateTimeKind.Local).AddTicks(2578));

                    b.HasKey("FromAreaCode", "ToAreaCode");

                    b.HasIndex("ToAreaCode");

                    b.ToTable("Calls");

                    b.HasData(
                        new
                        {
                            FromAreaCode = (byte)68,
                            ToAreaCode = (byte)82,
                            PricePerMinute = 1.9f
                        },
                        new
                        {
                            FromAreaCode = (byte)82,
                            ToAreaCode = (byte)68,
                            PricePerMinute = 2.9f
                        },
                        new
                        {
                            FromAreaCode = (byte)68,
                            ToAreaCode = (byte)96,
                            PricePerMinute = 1.7f
                        },
                        new
                        {
                            FromAreaCode = (byte)96,
                            ToAreaCode = (byte)68,
                            PricePerMinute = 2.7f
                        },
                        new
                        {
                            FromAreaCode = (byte)82,
                            ToAreaCode = (byte)96,
                            PricePerMinute = 0.9f
                        },
                        new
                        {
                            FromAreaCode = (byte)96,
                            ToAreaCode = (byte)82,
                            PricePerMinute = 1.9f
                        });
                });

            modelBuilder.Entity("FaleMaisDomain.Entities.Call", b =>
                {
                    b.HasOne("FaleMaisDomain.Entities.AreaCode", "From")
                        .WithMany("FromTo")
                        .HasForeignKey("FromAreaCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaleMaisDomain.Entities.AreaCode", "To")
                        .WithMany("ToFrom")
                        .HasForeignKey("ToAreaCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
