// <auto-generated />
using System;
using FaleMaisPersistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FaleMaisPersistence.Migrations
{
    [DbContext(typeof(FaleMaisDbContext))]
    [Migration("20200901213808_AlterTablesRelations2")]
    partial class AlterTablesRelations2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FaleMaisDomain.Entities.City", b =>
                {
                    b.Property<byte>("AreaCode")
                        .HasColumnName("area_code")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 38, 7, 970, DateTimeKind.Local).AddTicks(218));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 38, 7, 974, DateTimeKind.Local).AddTicks(6429));

                    b.HasKey("AreaCode");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("FaleMaisDomain.Entities.Price", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 38, 7, 978, DateTimeKind.Local).AddTicks(584));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("FromAreaCode")
                        .HasColumnName("from_area_code")
                        .HasColumnType("smallint");

                    b.Property<float>("PricePerMinute")
                        .HasColumnName("price_per_minute")
                        .HasColumnType("real");

                    b.Property<byte>("ToAreaCode")
                        .HasColumnName("to_area_code")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 9, 1, 18, 38, 7, 978, DateTimeKind.Local).AddTicks(983));

                    b.HasKey("Id");

                    b.HasIndex("FromAreaCode");

                    b.HasIndex("ToAreaCode");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("FaleMaisDomain.Entities.Price", b =>
                {
                    b.HasOne("FaleMaisDomain.Entities.City", "FromCity")
                        .WithMany("PricesToFrom")
                        .HasForeignKey("FromAreaCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaleMaisDomain.Entities.City", "ToCity")
                        .WithMany("PricesFromTo")
                        .HasForeignKey("ToAreaCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
